services:
  javascript-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: javascript-app
    restart: unless-stopped
    init: true
    ports:
      - "3000:3000"  # Exposed by Dockerfile
    # env_file: ./.env  # Uncomment if .env file exists
    # No external dependencies detected
